conifg_name: "app_full"
root: "${BITGEN_ROOT}/datasets/"

apps:
  ######## ANMLZoo
  - name: "Brill"
    type: "file"
    regex: "ANMLZoo/Brill/regex/brill.1chip.icgrep.anml.unique.regex"
    input: "ANMLZoo/Brill/inputs/brill_1MB.input"
  - name: "CAV"
    type: "file"
    regex: "ANMLZoo/ClamAV/regex/515_nocounter.1chip.icgrep.anml.unique.regex"
    input: "ANMLZoo/ClamAV/inputs/vasim_1MB.input"
  - name: "Dotstar"
    type: "file"
    regex: "ANMLZoo/Dotstar/regex/backdoor_dotstar.1chip.regex.icgrep.anml.unique.pcre"
    input: "ANMLZoo/Dotstar/inputs/backdoor_1MB.input"
  - name: "Protomata"
    type: "file"
    regex: "ANMLZoo/Protomata/regex/2340sigs.1chip.icgrep.anml.unique.regex"
    input: "ANMLZoo/Protomata/inputs/uniprot_fasta_1MB.input"
  - name: "Snort"
    type: "file"
    regex: "ANMLZoo/Snort/regex/snort.1chip.fix.icgrep.anml.unique.regex"
    input: "ANMLZoo/Snort/inputs/snort_1MB.input"

  ######## AutomataZoo
  - name: "Yara"
    type: "file"
    regex: "AutomataZoo/YARA/code/YARA_wide_rules.icgrep.anml.unique.txt"
    input: "AutomataZoo/YARA/benchmarks/YARA_wide/inputs/malware_malz3.input"

  ######## Regex
  - name: "Bro217"
    type: "file"
    regex: "Regex/Bro217/regex/bro217.re.icgrep.anml.unique.regex"
    input: "Regex/Bro217/inputs/bro217_depth_s0_p0.75.trace.input"
  - name: "ExactMatch"
    type: "file"
    regex: "Regex/ExactMath/regex/exact-math.conf_300-0.re.icgrep.anml.unique.regex"
    input: "Regex/ExactMath/inputs/exact-math_depth_s0_p0.75.trace.input"
  - name: "Ranges1"
    type: "file"
    regex: "Regex/Ranges1/regex/ranges1.conf_300-0.re.icgrep.anml.unique.regex"
    input: "Regex/Ranges1/inputs/ranges1_depth_s0_p0.75.trace.input"
  - name: "TCP"
    type: "file"
    regex: "Regex/TCP/regex/ranges05.conf_300-0.re.icgrep.anml.unique.regex"
    input: "Regex/TCP/inputs/TCP_1MB.input"

  ######## XML
  # - name: "xml"
  #   type: "xml"
  #   input: "xml/uwm.xml"

